// @ts-ignore
import { X, Plus, Minus, Trash2 } from "lucide-react";
import React, { useState } from "react";
import { Button } from "../../ui/button";
import { Input } from "../../ui/input";
import { Textarea } from "../../ui/textarea";
import { Select } from "../../ui/select";
import { Card } from "../../ui/card";
import { Badge } from "../../ui/badge";
import { Invoice, Product, User, CartItem } from "../../../types";
import {
  createInvoice,
  createOrUpdateUserInFirestore,
} from "../../../services/firestore-service";
import { toast } from "sonner";
import { CustomerSelectModal } from "./CustomerSelectModal";

interface CreateInvoiceFormProps {
  products: Product[];
  customers: User[];
  onSuccess: () => void;
  onCancel: () => void;
}

export function CreateInvoiceForm({
  products,
  customers,
  onSuccess,
  onCancel,
}: CreateInvoiceFormProps) {
  const [selectedCustomer, setSelectedCustomer] = useState<User | null>(null);
  const [showCustomerModal, setShowCustomerModal] = useState(false);
  const [invoiceItems, setInvoiceItems] = useState<CartItem[]>([]);
  const [taxRate, setTaxRate] = useState<number>(0);
  const [discount, setDiscount] = useState<number>(0);
  const [paymentMethod, setPaymentMethod] = useState<
    "cash" | "card" | "upi" | "cheque" | "bank-transfer"
  >("cash");
  const [paymentStatus, setPaymentStatus] = useState<
    "paid" | "pending" | "partial"
  >("paid");
  const [notes, setNotes] = useState("");
  const [isCreating, setIsCreating] = useState(false);

  const paymentMethods = [
    { value: "cash", label: "Cash" },
    { value: "card", label: "Card" },
    { value: "upi", label: "UPI" },
    { value: "cheque", label: "Cheque" },
    { value: "bank-transfer", label: "Bank Transfer" },
  ];

  const paymentStatuses = [
    { value: "paid", label: "Paid" },
    { value: "pending", label: "Pending" },
    { value: "partial", label: "Partial" },
  ];

  const calculateSubtotal = () => {
    return invoiceItems.reduce(
      (sum, item) => sum + item.product.retailPrice * item.quantity,
      0,
    );
  };

  const subtotal = calculateSubtotal();
  const taxAmount = (subtotal * taxRate) / 100;
  const discountAmount = discount || 0;
  const total = subtotal + taxAmount - discountAmount;

  const handleAddProduct = (product: Product) => {
    const existingItem = invoiceItems.find(
      (item) => item.product.id === product.id,
    );
    if (existingItem) {
      setInvoiceItems(
        invoiceItems.map((item) =>
          item.product.id === product.id
            ? { ...item, quantity: Math.min(item.quantity + 1, product.stock) }
            : item,
        ),
      );
    } else {
      setInvoiceItems([...invoiceItems, { product, quantity: 1 }]);
    }
  };

  const handleUpdateQuantity = (productId: string, quantity: number): void => {
    const product = invoiceItems.find(
      (item) => item.product.id === productId,
    )?.product;
    if (product && quantity > 0 && quantity <= product.stock) {
      setInvoiceItems(
        invoiceItems.map((item) =>
          item.product.id === productId ? { ...item, quantity } : item,
        ),
      );
    }
  };

  const handleRemoveItem = (productId: string): void => {
    setInvoiceItems(
      invoiceItems.filter((item) => item.product.id !== productId),
    );
  };

  const handleCreateInvoice = async () => {
    if (!selectedCustomer) {
      toast.error("Please select a customer");
      return;
    }

    if (invoiceItems.length === 0) {
      toast.error("Please add at least one product to the invoice");
      return;
    }

    setIsCreating(true);
    try {
      const invoiceData: Omit<Invoice, "id"> = {
        invoiceNumber: "", // Will be generated by service
        customerId: selectedCustomer.id,
        customerName: selectedCustomer.name,
        customerEmail: selectedCustomer.email,
        customerPhone: selectedCustomer.phone || "",
        customerAddress: selectedCustomer.addresses?.[0]?.addressLine1 || "",
        items: invoiceItems,
        subtotal,
        tax: taxAmount,
        discount: discountAmount,
        total,
        paymentMethod,
        paymentStatus,
        notes,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      await createInvoice(invoiceData);
      toast.success("Invoice created successfully");
      onSuccess();
    } catch (error) {
      console.error("Error creating invoice:", error);
      toast.error("Failed to create invoice");
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Customer Selection */}
      <div className="space-y-2">
        <label className="text-sm font-medium text-slate-700">Customer *</label>
        <div className="flex gap-2">
          {selectedCustomer ? (
            <div className="flex-1 p-3 border border-blue-200 bg-blue-50 rounded-lg">
              <p className="font-medium text-slate-800">
                {selectedCustomer.name}
              </p>
              <p className="text-sm text-slate-600">{selectedCustomer.phone}</p>
            </div>
          ) : (
            <div className="flex-1 p-3 border border-red-200 bg-red-50 rounded-lg">
              <p className="text-sm text-red-600">No customer selected</p>
            </div>
          )}
          <Button
            type="button"
            variant="outline"
            onClick={() => setShowCustomerModal(true)}
          >
            Change Customer
          </Button>
        </div>
      </div>

      {/* Products Section */}
      <div className="space-y-3">
        <label className="text-sm font-medium text-slate-700">
          Add Products to Invoice *
        </label>
        <div className="bg-slate-50 border border-slate-200 rounded-lg p-4 max-h-60 overflow-y-auto">
          <div className="space-y-2">
            {products.length === 0 ? (
              <p className="text-center text-slate-500 text-sm py-4">
                No products available
              </p>
            ) : (
              products.map((product) => (
                <div
                  key={product.id}
                  className="flex items-center justify-between p-2 hover:bg-white rounded border border-transparent hover:border-slate-200 transition-all"
                >
                  <div className="flex-1">
                    <p className="text-sm font-medium text-slate-800">
                      {product.name}
                    </p>
                    <p className="text-xs text-slate-500">
                      ₹{product.retailPrice.toLocaleString()} (Stock:{" "}
                      {product.stock})
                    </p>
                  </div>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => handleAddProduct(product)}
                    disabled={product.stock === 0}
                  >
                    <Plus size={16} />
                  </Button>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Invoice Items */}
      {invoiceItems.length > 0 && (
        <div className="space-y-3">
          <label className="text-sm font-medium text-slate-700">
            Invoice Items ({invoiceItems.length})
          </label>
          <Card className="p-0 overflow-hidden border-slate-200">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="bg-slate-100 border-b">
                  <tr>
                    <th className="px-4 py-2 text-left font-semibold text-slate-700">
                      Product
                    </th>
                    <th className="px-2 py-2 text-center font-semibold text-slate-700">
                      Price
                    </th>
                    <th className="px-2 py-2 text-center font-semibold text-slate-700">
                      Qty
                    </th>
                    <th className="px-2 py-2 text-center font-semibold text-slate-700">
                      Total
                    </th>
                    <th className="px-2 py-2 text-center font-semibold text-slate-700">
                      Action
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {invoiceItems.map((item) => (
                    <tr
                      key={item.product.id}
                      className="border-b hover:bg-slate-50"
                    >
                      <td className="px-4 py-2">
                        <p className="font-medium text-slate-800">
                          {item.product.name}
                        </p>
                        <p className="text-xs text-slate-500">
                          SKU: {item.product.sku}
                        </p>
                      </td>
                      <td className="px-2 py-2 text-center">
                        ₹{item.product.retailPrice.toLocaleString()}
                      </td>
                      <td className="px-2 py-2">
                        <div className="flex items-center justify-center gap-1">
                          <button
                            onClick={() =>
                              handleUpdateQuantity(
                                item.product.id,
                                item.quantity - 1,
                              )
                            }
                            className="p-1 hover:bg-slate-200 rounded"
                          >
                            <Minus size={14} />
                          </button>
                          <span className="w-8 text-center font-medium">
                            {item.quantity}
                          </span>
                          <button
                            onClick={() =>
                              handleUpdateQuantity(
                                item.product.id,
                                item.quantity + 1,
                              )
                            }
                            className="p-1 hover:bg-slate-200 rounded"
                          >
                            <Plus size={14} />
                          </button>
                        </div>
                      </td>
                      <td className="px-2 py-2 text-center font-bold text-slate-800">
                        ₹
                        {(
                          item.product.retailPrice * item.quantity
                        ).toLocaleString()}
                      </td>
                      <td className="px-2 py-2 text-center">
                        <button
                          onClick={() => handleRemoveItem(item.product.id)}
                          className="p-1 hover:bg-red-50 rounded text-red-600"
                        >
                          <Trash2 size={16} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        </div>
      )}

      {/* Totals Section */}
      <Card className="p-4 bg-gradient-to-br from-slate-50 to-slate-100 border-slate-200">
        <div className="space-y-3">
          <div className="flex justify-between text-sm">
            <span className="text-slate-600">Subtotal</span>
            <span className="font-semibold text-slate-800">
              ₹{subtotal.toLocaleString()}
            </span>
          </div>

          <div className="flex gap-4 items-end">
            <div className="flex-1">
              <label className="text-xs font-medium text-slate-600 block mb-1">
                Tax Rate (%)
              </label>
              <Input
                type="number"
                min="0"
                max="100"
                step="0.5"
                value={taxRate}
                onChange={(e) => setTaxRate(parseFloat(e.target.value) || 0)}
                className="h-8"
              />
            </div>
            <div className="text-right">
              <span className="text-xs text-slate-600">Tax Amount</span>
              <p className="font-semibold text-slate-800">
                ₹{taxAmount.toLocaleString()}
              </p>
            </div>
          </div>

          <div className="flex gap-4 items-end">
            <div className="flex-1">
              <label className="text-xs font-medium text-slate-600 block mb-1">
                Discount Amount (₹)
              </label>
              <Input
                type="number"
                min="0"
                value={discount}
                onChange={(e) => setDiscount(parseFloat(e.target.value) || 0)}
                className="h-8"
              />
            </div>
            <div className="text-right">
              <span className="text-xs text-slate-600">After Discount</span>
              <p className="font-semibold text-slate-800">
                ₹{(subtotal + taxAmount - discountAmount).toLocaleString()}
              </p>
            </div>
          </div>

          <div className="border-t-2 border-slate-300 pt-3">
            <div className="flex justify-between text-lg">
              <span className="font-bold text-slate-800">Total Amount</span>
              <span className="font-bold text-blue-600 text-2xl">
                ₹{total.toLocaleString()}
              </span>
            </div>
          </div>
        </div>
      </Card>

      {/* Payment Details */}
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">
            Payment Method *
          </label>
          <div className="relative">
            <select
              value={paymentMethod}
              onChange={(e) =>
                setPaymentMethod(e.target.value as typeof paymentMethod)
              }
              className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              {paymentMethods.map((method) => (
                <option key={method.value} value={method.value}>
                  {method.label}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">
            Payment Status *
          </label>
          <div className="relative">
            <select
              value={paymentStatus}
              onChange={(e) =>
                setPaymentStatus(e.target.value as typeof paymentStatus)
              }
              className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              {paymentStatuses.map((status) => (
                <option key={status.value} value={status.value}>
                  {status.label}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Notes */}
      <div className="space-y-2">
        <label className="text-sm font-medium text-slate-700">Notes</label>
        <Textarea
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Add any notes or special instructions..."
          rows={3}
        />
      </div>

      {/* Action Buttons */}
      <div className="flex gap-3 pt-4 border-t">
        <Button
          type="button"
          variant="outline"
          className="flex-1"
          onClick={onCancel}
          disabled={isCreating}
        >
          Cancel
        </Button>
        <Button
          type="button"
          variant="primary"
          className="flex-1"
          onClick={handleCreateInvoice}
          disabled={
            isCreating || !selectedCustomer || invoiceItems.length === 0
          }
        >
          {isCreating ? "Creating..." : "Create Invoice"}
        </Button>
      </div>

      {/* Customer Modal */}
      <CustomerSelectModal
        isOpen={showCustomerModal}
        customers={customers}
        onSelect={(customer: User) => {
          setSelectedCustomer(customer);
          setShowCustomerModal(false);
        }}
        onClose={() => setShowCustomerModal(false)}
        onCreateNew={(newCustomer: User) => {
          setSelectedCustomer(newCustomer);
          setShowCustomerModal(false);
        }}
      />
    </div>
  );
}
